### PR TITLE
Add support for postcss-less syntax

### PR DESCRIPTION
**Pull request by dloop-mb**
For now the plugin only supports SCSS postcss syntax.

Example:
create file _test.less_
```
// body {
//   display: none;
// }
```
run `prettier --check test.less`
will return the following:
```
test.less[error] test.less: CssSyntaxError: <css input>:2:6: Unknown word
[error]     at Input.error (/usr/lib/node_modules/postcss/lib/input.js:148:16)
[error]     at Parser.unknownWord (/usr/lib/node_modules/postcss/lib/parser.js:540:22)
[error]     at Parser.decl (/usr/lib/node_modules/postcss/lib/parser.js:219:16)
[error]     at Parser.other (/usr/lib/node_modules/postcss/lib/parser.js:128:18)
[error]     at Parser.parse (/usr/lib/node_modules/postcss/lib/parser.js:72:16)
[error]     at parse (/usr/lib/node_modules/postcss/lib/parse.js:11:12)
[error]     at new LazyResult (/usr/lib/node_modules/postcss/lib/lazy-result.js:133:16)
[error]     at Processor.process (/usr/lib/node_modules/postcss/lib/processor.js:28:14)
[error]     at /usr/lib/node_modules/prettier-plugin-css-order/src/sorter.js:8:6
[error]     at runAsWorker (/usr/lib/node_modules/prettier-plugin-css-order/node_modules/sync-threads/src/index.js:48:18)
```

This pull request adds support for postcss-less the same way it already supports postcss-scss.

### CODE REVIEW

**Comment by Siilwyn** [comment]
:wave: thank you for your contribution! I've made some small changes, let me know if it looks good then I'll merge and release soonish. :)

https://github.com/dloop-mb/prettier-plugin-css-order/pull/1

**Comment by dloop-mb** [comment]
Perfect :+1:, looking forward to the release :wink:

**Comment by Siilwyn** [comment]
Created a new PR to fix the linting issue.

**Comment by Siilwyn** [comment]
Again thank you for the PR! :)

**Comment by dloop-mb** [comment]
Anytime!

**Pull request closed without merging**
